services:
  # Docker worker that launches each flow run as a Docker container
  prefect-docker-worker:
    image: prefecthq/prefect:3-latest
    environment:
      PREFECT_API_URL: http://host.docker.internal:4200/api
      ENVIRONMENT: localMachineDockerWorker
      #PREFECT_API_AUTH_STRING: username:password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -lc "pip install -q prefect-docker &&
      prefect worker start --pool docker-pool-lambda --type docker"
    restart: on-failure
